# -*- coding: utf-8 -*-
"""Visualizations (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSgkTa6RI3fTbwobI5a6lVhRgCENrPde
"""

import glob
import re
import itertools
import numpy as np
import matplotlib.pyplot as plt

file = glob.glob("./*.txt")[0]

ls = []
with open(file, 'r') as f:
    lines = f.readlines()
    for j in range(len(lines)):
        if lines[j] != "\n":
            ls.append(lines[j])

def grouper(n, iterable):
    args = [iter(iterable)]*n
    return ([e for e in t if e!=None ] for t in itertools.zip_longest(*args))

gen=grouper(101, ls)

ls2 = []
for i in gen:
    ls2.append(i)

ls2[0]

ls3 = []
for i in range(len(ls2)):
    ls4 = []
    for j in ls2[i]:
        k = re.findall("[0].[0-9][0-9][0-9][0-9][0-9][0-9]",j)
        if k != []:
            for l in k:
                ls4.append(l)
    ls3.append(ls4)

ls3

pt1 = []
for i in ls3[0]:
    pt1.append(float(i))
print(pt1[0:10])

plt.plot(pt1)

pt2 = []
for i in ls3[1]:
    pt2.append(float(i))
print(pt2[0:10])

plt.plot(pt2)

pt3 = []
for i in ls3[2]:
    pt3.append(float(i))
print(pt3[0:10])

plt.plot(pt3)

pt4 = []
for i in ls3[3]:
    pt4.append(float(i))
print(pt4[0:10])

plt.plot(pt4)

pt5 = []
for i in ls3[4]:
    pt5.append(float(i))
print(pt5[0:10])

plt.plot(pt5)

